# -*- coding: utf-8 -*-
import os

SECRET_KEY=os.environ.get('SECRET_KEY')
SQLALCHEMY_DATABASE_URI=os.environ.get('DATABASE_URL')
SQLALCHEMY_ECHO=True
SQLALCHEMY_TRACK_MODIFICATIONS=False

CSRF_SESSION_KEY=os.environ.get('SECRET_KEY')
